env:
  browser: true
  node: true
  jquery: true
globals:
  Rails: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 7
  sourceType: module
parser: "babel-eslint"
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
