version: 2

jobs:
  minitest:
    working_directory: ~/reddhub
    docker:
      - image: circleci/ruby:2.5.1-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: reddhub_test
    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
          keys:
            - reddhub-bundle-v1-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: bundle check || bundle install

      - save_cache:
          key: reddhub-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          name: Restore Yan Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:migrate

      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: Run minitest
          command: bundle exec rake

  js:
    working_directory: ~/reddhub
    docker:
      - image: circleci/ruby:2.5.1-node
    steps:
      - checkout

      - restore_cache:
          name: Restore Yan Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Prettier
          command: yarn run prettier

      - run:
          name: Lint
          command: yarn run lint

      - run:
          name: Jest
          command: yarn test

  deployment:
    working_directory: ~/reddhub
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  pipeline:
    jobs:
      - js
      - minitest:
          requires:
            - js
      - deployment:
          requires:
            - minitest
          filters:
            branches:
              only: master
