test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>
  google_project: <%= ENV["GOOGLE_PROJECT"] %>
  google_credentials: <%= ENV["GOOGLE_CREDENTIALS"] %>
  google_bucket: <%= ENV["GOOGLE_BUCKET"] %>
  amazon_access_key_id: <%= ENV["AMAZON_ACCESS_KEY_ID"] %>
  amazon_secret_access_key: <%= ENV["AMAZON_SECRET_ACCESS_KEY"] %>
  amazon_region: <%= ENV["AMAZON_REGION"] %>
  amazon_bucket: <%= ENV["AMAZON_BUCKET"] %>
